services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      - DB_DRIVER=${DB_DRIVER:-duckdb}
      - CLICKHOUSE_URL=${CLICKHOUSE_URL:-http://clickhouse:8123}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-anthropic.claude-3-5-sonnet-20240620-v1:0}
      # USE_OLLAMA, OLLAMA_URL, and OLLAMA_MODEL are loaded from .env via env_file
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ../backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - clickhouse

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:${BACKEND_PORT:-8000}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ../frontend:/app
    depends_on:
      - backend

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

